#!/usr/bin/env bash
# publish file to web server using scp

# Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
#	 $0              $1           $2 $3       $4
scp -i "$4" "$1" "$3"@"$2":~/   
