#!/usr/bin/env bash
# publish file to web server using scp
# Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
#        $0              $1           $2 $3       $4

sed -i "s/^#*.*StrictHostKeyChecking\s*.*$/    StrictHostKeyChecking no/g" \
        /etc/ssh/ssh_config
service ssh reload
if [ "$#" -lt 3 ]; then
        echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
        exit 1
fi
if [ "$4" ]; then
         scp -i "$4" "$1" "$3"@"$2":~/
else
         scp "$1" "$3"@"$2":~/
fi
