#!/bin/bash
# install nginx on a new ubuntu server

sudo su
apt update
apt install -y nginx
service nginx start
apt install -y ufw
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 80/tcp
ufw --force enable
# echo "Hello World!" > /var/www/html/index.html

# add redirect line
line1="\tserver_name _;"
line2="\trewrite \/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sed -i "s/^[[:blank:]]server_name _;/$line1\n$line2/" \
	/etc/nginx/sites-enabled/default

service nginx reload
exit
