#!/usr/bin/env bash
# install nginx on a new ubuntu server, with custom nginx header and haproxy

apt update && apt upgrade -y
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.0
apt-get install haproxy=2.0.\*
haproxy -v
apt update && apt upgrade -y

#apt install -y nginx
#service nginx start
#apt install -y ufw
#ufw default deny incoming
#ufw default allow outgoing
#ufw allow 22/tcp
#ufw allow 80/tcp
#ufw --force enable
#echo "Hello World!" > /var/www/html/index.html

#service nginx restart
~
