#!/usr/bin/env bash
# install brand new Load Balancer Ubuntu server
# passwordless sudo privilege or root account is required to run this script

#update and upgrade system first
echo Running Update and Upgrade... && echo
sudo apt update
sudo apt upgrade -y

# Install ufw and configure ports
echo Configuring firewall... && echo
sudo apt install -y ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443
sudo ufw --force enable
echo Firewall done. && echo

echo Acquiring Haproxy repo... && echo
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.0 -y

echo Installing HAProxy 2.0... && echo
sudo apt-get install haproxy=2.0.\* -y

# configure haproxy:
echo Configuring HAProxy 2.0... && echo

echo "
frontend myfrontend
  bind 0.0.0.0:80
  default_backend myservers

backend myservers
  balance roundrobin
  server web-01 158178-web-01:80 check
  server web-02 158178-web-02:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

# ensure HAproxy can be managed via an init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy start

haproxy -v
echo Haproxy Installed and configured. && echo

# configure /etc/hosts - replace ip and hostnames as required
echo "Configuring /etc/hosts..." && echo
echo "35.175.135.222 158178-web-01 web-01" | sudo tee -a /etc/hosts
echo "52.3.240.190 158178-web-02 web-02"   | sudo tee -a /etc/hosts
echo "54.237.11.232 158178-lb-01 lb-01"    | sudo tee -a /etc/hosts


echo '--- END OF SCRIPT ---'
