#!/usr/bin/env bash
# install nginx on a new ubuntu server, with custom nginx header and haproxy

echo Running Update and Upgrade... && echo
apt update && apt upgrade -y

echo Acquiring Haproxy repo... && echo
apt-get install --no-install-recommends software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-2.0 -y

echo Installing HAProxy 2.0... && echo
apt-get install haproxy=2.0.\* -y

haproxy -v
echo Installation done. && echo
echo Running Update and Upgrade again...
apt update && apt upgrade -y

# ensure HAproxy can be managed via an init script
echo "ENABLED=1" >> /etc/default/haproxy

# configure /etc/hosts
echo "35.175.135.222 158178-web-01 web-01" >> /etc/hosts
echo "52.3.240.190 158178-web-02 web-02" >> /etc/hosts
echo "54.237.11.232 158178-lb-01 lb-01" >> /etc/hosts

# configure haproxy:
echo "
frontend myfrontend
  bind 0.0.0.0:80
  default_backend myservers

backend myservers
  balance roundrobin
  server web-01 158178-web-01:80 check
  server web-02 158178-web-02:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy reload

echo '--- END OF SCRIPT ---'
