#!/usr/bin/env bash
# Debug my nginx web server to listen on port 80
sed -i 's/listen 8080 default_server/listen 80 default_server/' \
        /etc/nginx/sites-enabled/default
sudo service nginx stop
