#!/usr/bin/env bash
# This script does the following:
# manages my rocess

if [ "$#" -ne 2 ] || ([ "$1" -ne "start" ]\
	&& [ "$1" -ne "stop" ]\
	&& [ "$1" -ne "restart" ]); then
	echo "Usage: manage_my_process {start|stop|restart}"
fi
pgrep -f "$0" > /var/run/my_process.pid

if [ "$1" -eq "start" ]; then
	# do start
elif [ "$1" -eq "stop" ]; then
	# do stop
elif [ "$1" -eq "stop" ]; then
	# do restart
fi
