#!/usr/bin/env bash
# This script does the following:
# manages my rocess

if [ "$#" -ne 2 ] && { [ "$1" != "start" ]\
	&& [ "$1" != "stop" ]\
	&& [ "$1" != "restart" ]; }; then
	echo "Usage: manage_my_process {start|stop|restart}"
	exit 1
fi

pgrep -f "$0" > /var/run/my_process.pid

if [ "$1" = "start" ]; then
	# do start
	echo "starting..."
elif [ "$1" = "stop" ]; then
	# do stop
	echo "stopping..."
elif [ "$1" = "restart" ]; then
	# do restart
	echo "restarting..."
fi
