#!/usr/bin/env bash
# This script does the following:
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when 
# receiving a SIGQUIT or SIGTERM signal

pgrep -f "$0" > /var/run/myscript.pid

# display to infinity and beyond waiting 2 secs in between, indefinitely

trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"; if [ -e "/var/run/myscript.pid" ]; then rm "/var/run/myscript.pid"; fi; exit 1' SIGTERM
trap 'if [ -e "/var/run/myscript.pid" ]; then rm "/var/run/myscript.pid"; fi; exit 1' SIGQUIT

while true; do
	echo "To infinity and beyond"
	sleep 2
done
