#!/usr/bin/env bash
# Ping a given IP address

cp /etc/hosts ~/hosts.new

sed -i "s/^127.0.0.1.*localhost$/127.0.0.2	localhost/" ~/hosts.new
sed -i "s/^157.240.11.35.*facebook.com$/8.8.8.8	facebook.com/" ~/hosts.new

if grep -q ".*facebook.com$" ~/hosts.new; then
	sed -i "s/.*facebook.com$/8.8.8.8 facebook.com/" ~/hosts.new
else
	echo "8.8.8.8	facebook.com" >> ~/hosts.new
fi

cp ~/hosts.new /etc/hosts
